"""
KML 文件导出器模块

将 GPS 轨迹和位置点导出为 KML 格式，可在 Google Earth 等应用中查看。
"""

from typing import List, Tuple, Optional
from datetime import datetime


class KMLExporter:
    """KML 文件导出器"""

    def __init__(self):
        self.places = []
        self.tracks = []
        self.styles = {}

    def add_placemark(
        self,
        name: str,
        latitude: float,
        longitude: float,
        altitude: Optional[float] = None,
        description: str = ""
    ) -> None:
        """
        添加一个位置标记
        
        Args:
            name: 位置名称
            latitude: 纬度（十进制度数）
            longitude: 经度（十进制度数）
            altitude: 海拔高度（米），可选
            description: 位置描述
        """
        placemark = {
            'name': name,
            'latitude': latitude,
            'longitude': longitude,
            'altitude': altitude,
            'description': description
        }
        self.places.append(placemark)

    def add_track(
        self,
        points: List[Tuple[float, float]],
        name: str = "GPS Track",
        color: str = "ff0000ff",  # KML 颜色格式: aabbggrr (alpha, blue, green, red)
        width: int = 2
    ) -> None:
        """
        添加一条轨迹线
        
        Args:
            points: 坐标点列表 [(lat1, lon1), (lat2, lon2), ...]
            name: 轨迹名称
            color: 线条颜色（KML 格式：aabbggrr）
            width: 线条宽度
        """
        track = {
            'name': name,
            'points': points,
            'color': color,
            'width': width
        }
        self.tracks.append(track)

    def _generate_placemark_kml(self, placemark: dict) -> str:
        """生成单个位置标记的 KML"""
        name = placemark['name']
        lat = placemark['latitude']
        lon = placemark['longitude']
        alt = placemark['altitude'] if placemark['altitude'] else 0
        desc = placemark['description']

        return f"""
      <Placemark>
        <name>{name}</name>
        <description>{desc}</description>
        <Point>
          <coordinates>{lon},{lat},{alt}</coordinates>
        </Point>
      </Placemark>"""

    def _generate_track_kml(self, track: dict) -> str:
        """生成单条轨迹的 KML"""
        name = track['name']
        color = track['color']
        width = track['width']
        points = track['points']

        # 生成坐标字符串
        coordinates = []
        for lat, lon in points:
            coordinates.append(f"{lon},{lat},0")
        coord_string = " ".join(coordinates)

        return f"""
      <Placemark>
        <name>{name}</name>
        <Style>
          <LineStyle>
            <color>{color}</color>
            <width>{width}</width>
          </LineStyle>
        </Style>
        <LineString>
          <tessellate>1</tessellate>
          <coordinates>{coord_string}</coordinates>
        </LineString>
      </Placemark>"""

    def save(self, filepath: str) -> bool:
        """
        保存 KML 文件
        
        Args:
            filepath: 输出文件路径
        
        Returns:
            是否保存成功
        """
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
                f.write('<kml xmlns="http://www.opengis.net/kml/2.2">\n')
                f.write('  <Document>\n')
                f.write(f'    <name>GPS Track</name>\n')
                f.write(f'    <description>Generated by GPS NMEA Parser</description>\n')

                # 写入位置标记
                for placemark in self.places:
                    f.write(self._generate_placemark_kml(placemark))

                # 写入轨迹
                for track in self.tracks:
                    f.write(self._generate_track_kml(track))

                f.write('  </Document>\n')
                f.write('</kml>\n')

            return True
        except Exception as e:
            print(f"错误：保存 KML 文件失败 - {e}")
            return False

    def clear(self) -> None:
        """清除所有数据"""
        self.places = []
        self.tracks = []

    @staticmethod
    def create_simple_kml(
        filepath: str,
        points: List[Tuple[float, float]],
        track_name: str = "GPS Track"
    ) -> bool:
        """
        快速创建简单的 KML 文件（只包含轨迹）
        
        Args:
            filepath: 输出文件路径
            points: 坐标点列表 [(lat1, lon1), (lat2, lon2), ...]
            track_name: 轨迹名称
        
        Returns:
            是否保存成功
        """
        exporter = KMLExporter()
        exporter.add_track(points, name=track_name)
        return exporter.save(filepath)
